### ISSUE TITLE
Python > 3.6 should not install the forked wired from the requirements

### ISSUE THREAD

**Issue by hanfried** [pauleveritt/42-workshop#5]
I followed the instructions from the website with Python 3.8.0 and got always this strange error message:
```
(env) ➜  fortytwo git:(master) python s01_find_action.py 
Traceback (most recent call last):
  File "s01_find_action.py", line 17, in <module>
    from fortytwo import App, Greeter
  File "/home/janek/Repositories/42-workshop/fortytwo/__init__.py", line 4, in <module>
    from fortytwo import models
  File "/home/janek/Repositories/42-workshop/fortytwo/models.py", line 3, in <module>
    from wired.dataclasses import factory
ModuleNotFoundError: No module named 'wired.dataclasses'
```
In the end what solved the problem was to `pip uninistall wired` the wired-0.2 version from the requirements.txt (pointing to a forked wired at https://github.com/pauleveritt/wired). If I run after installing this forked version, `pip install wired`, I get wired-0.2.1 (a minor version ahead) installed, and everything works fine.

I think, it's confusing that following the tutorial (and/or installing the requirements.txt) leads to a non working configuration. There's a certainly a reason for the usage of the fork, but either it is deprecated over time or at least it doesn't matter for modern Python, does it? It would already be helpful to get a hint in the README about :thinking:

**Comment by pauleveritt** [comment]
You're right, that fork was merged and I didn't clean up this repo. I just pushed a commit that has what you did.
